import { GoogleGenAI, Type, Schema } from "@google/genai";
import { Project, DeployPlan } from "../types";

// Initialize Gemini
const ai = new GoogleGenerativeAI({
  apiKey: import.meta.env.VITE_API_KEY as string,
});


// Schema definition for the structured output
const configFileSchema: Schema = {
  type: Type.OBJECT,
  properties: {
    fileName: { type: Type.STRING, description: "Nome do arquivo, ex: vercel.json" },
    content: { type: Type.STRING, description: "O conteúdo completo do arquivo de configuração" },
    language: { type: Type.STRING, description: "A linguagem do arquivo, ex: json, yaml, dockerfile" }
  },
  required: ["fileName", "content", "language"]
};

const stepSchema: Schema = {
  type: Type.OBJECT,
  properties: {
    id: { type: Type.STRING, description: "ID único para o passo, ex: step-1" },
    title: { type: Type.STRING, description: "Título curto do passo (em Português)" },
    description: { type: Type.STRING, description: "Explicação detalhada do que fazer (em Português)" },
    commands: { 
      type: Type.ARRAY, 
      items: { type: Type.STRING },
      description: "Comandos de terminal para executar, se houver"
    },
    configFiles: {
      type: Type.ARRAY,
      items: configFileSchema,
      description: "Arquivos de configuração para criar durante este passo, se houver"
    },
    notes: { type: Type.STRING, description: "Avisos importantes ou dicas (em Português)" }
  },
  required: ["id", "title", "description"]
};

const planSchema: Schema = {
  type: Type.OBJECT,
  properties: {
    steps: { 
      type: Type.ARRAY, 
      items: stepSchema 
    },
    prerequisites: {
      type: Type.ARRAY,
      items: { type: Type.STRING },
      description: "Lista de ferramentas ou contas necessárias antes de começar (em Português)"
    },
    warnings: {
      type: Type.ARRAY,
      items: { type: Type.STRING },
      description: "Armadilhas comuns para esta stack (em Português)"
    }
  },
  required: ["steps", "prerequisites", "warnings"]
};

export const generateDeployPlan = async (project: Project): Promise<DeployPlan> => {
  const model = "gemini-2.5-flash";
  
  const prompt = `
    Você é um Arquiteto DevOps Sênior. Crie um guia de deploy detalhado, passo a passo, para o seguinte projeto:
    
    Nome do Projeto: ${project.name}
    Tipo: ${project.type}
    Frontend/Stack Tecnológico: ${project.techStack.join(', ')}
    Backend: ${project.backend || 'Nenhum'}
    Banco de Dados: ${project.database || 'Nenhum'}
    Alvo de Hospedagem (Hosting): ${project.hostingTarget}
    Sistema Operacional do Desenvolvedor: ${project.os}

    O objetivo é levar este projeto do desenvolvimento local para produção.
    Inclua arquivos de configuração específicos (como netlify.toml, vercel.json, wrangler.toml, Dockerfile, github-workflows, etc.) quando aplicável.
    Forneça comandos de terminal específicos para o Sistema Operacional do desenvolvedor (${project.os}).
    
    IMPORTANTE: Todo o texto (títulos, descrições, notas) deve estar estritamente em Português do Brasil (pt-BR).
  `;

  try {
    const response = await ai.models.generateContent({
      model: model,
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: planSchema,
        systemInstruction: "Você é um assistente de DevOps prestativo e preciso. Sua saída deve ser um JSON válido aderindo ao esquema fornecido e o idioma deve ser Português do Brasil."
      }
    });

    const text = response.text;
    if (!text) throw new Error("Sem resposta da IA");
    
    const plan: DeployPlan = JSON.parse(text);
    
    // Add isCompleted flag which isn't generated by AI
    plan.steps = plan.steps.map(step => ({
      ...step,
      isCompleted: false
    }));

    return plan;

  } catch (error) {
    console.error("Erro ao gerar plano:", error);
    throw error;
  }
};